### PR TITLE
Add support for completion via company-mode

### PR DESCRIPTION
**Pull request by vedang**
... and also, enable smart-tab completion at end-of-line. 

I added support for company-mode to smart-tab, and when I opened Github to submit a pull request, I noticed that another PR - #9 - was pending merge with some suggestions. I've modified my patch to make those changes. 

Let me know if you have any feedback on these commits, and if these can be merged into master.

### CODE REVIEW

**Comment by vedang** [comment]
Any update on this?

**Comment by genehack** [comment]
Sorry, I've been helping put together a conference and that's been consuming all my open source time. At the conference now; hope to get a chance to look at this during hacking time at the end of the week. Thanks for the contribution and sorry for the delay in reviewing it.

**Comment by vedang** [comment]
No problem, thanks for letting me know.

**Comment by genehack** [comment]
Sorry for the *extreme* delay in getting back to you. 

I've reviewed this patch and would love to merge it, but I'm not comfortable with the change it makes to the default behavior. 

How would you feel about changing this to set the default value of `smart-tab-user-provided-completion-function` to be `ac-start`? (We'd also need to pass the `default-init` option.) 

I _think_ that would preserve the original behavior without requiring anyone to update configs while providing the customization point you're after.

**Comment by vedang** [comment]
I re-read the code and re-wrote it to maintain the default behavior. Please review it and let me know if the change looks good! :)

**Comment by genehack** [comment]
I just pushed some documentation level tweaks (and a version bump) to https://github.com/genehack/smart-tab/tree/company-and-eol. I've got that version loaded in my Emacs; assuming I don't run into any issues I'll merge to master later this weekend.

**Pull request merged**
